### ISSUE TITLE
Support wildcards when replacing

### ISSUE THREAD

**Issue by qiufmgm** [digitalw0lf/hextor#2]
First of all, thank you for developing this software.

Suggest to add features:
Support wildcards when replacing.

tks.

**Comment by digitalw0lf** [comment]
I thought of something like that, but could not decide on a suitable syntax.
Maybe like this:

In search pattern, every value in "{}" becomes a sub-expression. Values can be named by specifying an identifier after a type, e.g.: {u32 x: 0..99}
Also, every sequense in round brackets "()" becomes a sub-expression. It may contain several "{}" values inside, e.g.: ({ansi:'a'..'z':1..100}{u8:0})

In "replace" pattern, one can use sub-expression in two ways:
1) By index, like in RegExp: $1, $2 etc.
2) By names: $(x). It's possible to specify expressions with values, e.g: $(x+1) will increase found value

What do you think? Maybe you have some use cases which will give me new ideas.

(btw, first feedback on github. Glad to see)

**Comment by qiufmgm** [comment]
This is my idea:
For example, if I want to find out "33 ?? ?? 35" and I want to replace it with "EE 33 ?? BB" .
When writing to the file，Hextor does not care what byte is in the third position of Target hex values.

**Comment by qiufmgm** [comment]
Excuse me, my English is poor.

**Comment by digitalw0lf** [comment]
Ok, got it.
In RegExp-like syntax, it will be possible using this patterns: "33 ?? (??) 35" -> "EE 33 $1 BB"

**Comment by digitalw0lf** [comment]
It's early to close. This is not implemented yet)

**Comment by qiufmgm** [comment]
In hexadecimal mode, it is recommended to use ‘??’ as a wildcard instead of sub-expression mode

**Comment by digitalw0lf** [comment]
Done.
Docs: https://github.com/digitalw0lf/hextor/wiki/Search-and-replace#replacement-subexpression-substitution

An example from previous comment can be accomplished using:

Find `6A 00 (68 ?? ?? ?? ?? 68 ?? ?? ?? ?? 6A 00 E8 ?? ?? ?? ?? E8)`, replace with `EB 11 $1`
or
Find `6A 00 (68 {u8::4} 68 {u8::4} 6A 00 E8 {u8::4} E8)`, replace with `EB 11 $1`

**Comment by Max-RM** [comment]
> Ok, got it. In RegExp-like syntax, it will be possible using this patterns: "33 ?? (??) 35" -> "EE 33 $1 BB"

can you make such a Hex pattern work too: ?
example: 7? ?? B0 01 48 8? ?C
7? - where half of the byte is unknown.

**Comment by digitalw0lf** [comment]
> can you make such a Hex pattern work too: ? example: 7? ?? B0 01 48 8? ?C 7? - where half of the byte is unknown.

Hello.
Although not exactly like in your example, the same result can be achieved currently using the following syntax:

`{u8:0x70..0x7F} ?? B0 01 48 {u8:0x80..0x8F} {u8:0x0C,0x1C,0x2C,0x3C,0x4C,0x5C,0x6C,0x7C,0x8C,0x9C,0xAC,0xBC,0xCC,0xDC,0xEC,0xFC}`

Yes, I know it doesn't look very elegant. I'll keep it as a feature request for now.

@Max-RM   Can you please tell a bit more about use cases when you need to search for something like `?C` ?

**Comment by Max-RM** [comment]
> > can you make such a Hex pattern work too: ? example: 7? ?? B0 01 48 8? ?C 7? - where half of the byte is unknown.
> 
> Hello. Although not exactly like in your example, the same result can be achieved currently using the following syntax:
> 
> `{u8:0x70..0x7F} ?? B0 01 48 {u8:0x80..0x8F} {u8:0x0C,0x1C,0x2C,0x3C,0x4C,0x5C,0x6C,0x7C,0x8C,0x9C,0xAC,0xBC,0xCC,0xDC,0xEC,0xFC}`
> 
> Yes, I know it doesn't look very elegant. I'll keep it as a feature request for now.
> 
> @Max-RM Can you please tell a bit more about use cases when you need to search for something like ?`?C`

Thanks for answer.
About "use cases" it can help for searching Hex patterns with unknown half of byte.

**Comment by Max-RM** [comment]
> > can you make such a Hex pattern work too: ? example: 7? ?? B0 01 48 8? ?C 7? - where half of the byte is unknown.
> 
> Hello. Although not exactly like in your example, the same result can be achieved currently using the following syntax:
> 
> `{u8:0x70..0x7F} ?? B0 01 48 {u8:0x80..0x8F} {u8:0x0C,0x1C,0x2C,0x3C,0x4C,0x5C,0x6C,0x7C,0x8C,0x9C,0xAC,0xBC,0xCC,0xDC,0xEC,0xFC}`
> 
> Yes, I know it doesn't look very elegant. I'll keep it as a feature request for now.
> 
> [@Max-RM](https://github.com/Max-RM) Can you please tell a bit more about use cases when you need to search for something like `?C` ?

That's more actual for ARM binaries. Where unknown half-bytes is very common thing.

Is there any progress in solving this issue?
