### ISSUE TITLE
trying to compile with d10.2.3

### ISSUE THREAD

**Issue by limelect** [digitalw0lf/hextor#37]
missing 
intedimagepreoxy coparefram maybe more

**Comment by digitalw0lf** [comment]
As I already said, currently Hextor is not prepared to be compiled by everyone. It has some non-opensource dependencies from my commercial projects. So I don't think you will be able to build it, sorry.

**Comment by 7enDesign** [comment]
are these dependencies available commercially in binary only format, so that your product is protected and the build is then possible.

**Comment by 7enDesign** [comment]
I'm trying to build with Delphi 10.4 but cannot find a version of SuperObject that doesnt have some issue.

**Comment by digitalw0lf** [comment]
Well, I checked the sources and found out that things are not so bad. A couple of define's made it compilable, and the only missing thing is sampling profiler. Please update your repo clone and try again.

You also need to clone https://github.com/digitalw0lf/dwfunits.git next to Hextor folder.
For SuperObject, use https://github.com/fainspace/superobject

**Comment by 7enDesign** [comment]
Other dependencies are FastMM4, VirtualTrees and SynEdit.

Which repo/commit should I use for the SynEdit dependency?

**Comment by digitalw0lf** [comment]
Links to all dependencies are in the bottom of README.md. Usually master branch will do.

AppVersion.Inc is generated by ./Installer/MakeIncludes.sh. I use bash from WSL.
(or you can just paste `const AppVersion = 'v0.13';` into AppVersion.inc)
