### ISSUE TITLE
Add support for Windows ARM

### ISSUE THREAD

**Issue by Max-RM** [digitalw0lf/hextor#47]
Please compile it for Windows ARM32/ARM64
So it will be possible to use Hextor as native app without x86-arm translator

**Comment by digitalw0lf** [comment]
Hello.
Sorry, but AFAIK Delphi compiler doesn't support Windows ARM target yet.

**Comment by Max-RM** [comment]
> Hello. Sorry, but AFAIK Delphi compiler doesn't support Windows ARM target yet.

ок
