### ISSUE TITLE
Ability to remove data from files.

### ISSUE THREAD

**Issue by RedGreenBlue09** [digitalw0lf/hextor#48]
This feature is actually very crucial. There are many use cases like removing a redundant header from a file.

PS: This editor is the closest to HxD, supports HiDPI and is pretty lightweight (not as Hxd), which is why I prefer it over other free ones.

**Comment by digitalw0lf** [comment]
Hello.
If you press "Insert" key, it will switch from "overwrite" mode to "insert/delete" editing mode.
Is it what you are asking about?

**Comment by RedGreenBlue09** [comment]
I'll try later, thank you.

**Comment by RedGreenBlue09** [comment]
Yes, that's exactly what I need. Nonetheless, can you make it more accessible like adding a toggle to the toolbar or edit menu?

**Comment by RedGreenBlue09** [comment]
Amazing! Thank you.
